services:
  hdfs-gateway:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: hdfs-gateway

    network_mode: host

    environment:
      APP_NAME: HDFS Gateway API
      APP_ENV: production
      DEBUG: "false"
      HOST: 0.0.0.0
      PORT: 5005
      HDFS_NAMENODE_URL: ${HDFS_NAMENODE_URL:-http://localhost:9870}
      HDFS_USER: ${HDFS_USER:-suveer}
      HDFS_DEFAULT_DIR: /
      HDFS_TIMEOUT_SECONDS: 30

    restart: unless-stopped
